config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'

  resources :accounts, only: %i[show] do
    resources :followings, only: %i[index]
    resources :followers, only: %i[index]
    resources :follows, only: %i[create]
    resources :unfollows, only: %i[create]
  end

  resources :articles, only: %i[index new create] do
    resources :comments, only: %i[index new create]
  end

  scope module: :apps do
    resource :profile, only: %i[show edit update]
    resource :popular, only: %i[show]
  end

  namespace :api do
    scope '/articles/:article_id' do
      resources :comments, only: %i[index new create]
      resource :like, only: %i[show create destroy]
    end
  end
end

app/views/commons/_article.html.haml
.card
  .article-page
    = link_to account_path(article.user) do
      = image_tag article.user.avatar_image, class: 'avatar-tertiary'
    %div  
      %p.article-page_username= article.user.username
      %p.article-page_date= I18n.l(article.created_at, format: :default)
      
  .card-phots
    = image_tag article.images[0], class: 'card-img'
  .icons
    - if user_signed_in? 
      %div
        = image_tag 'heart-active.svg', class: 'active-heart hidden', id: "#{article.id}"
    %div
      = image_tag 'heart.svg', class: 'inactive-heart hidden', id: "#{article.id}"
    %div
      = link_to article_comments_path(article) do
        = image_tag 'comment.png', class: 'comment-img', id: "#{article.id}"
    .share-img
      = link_to "https://twitter.com/share?url=#{request.url}", title: 'Twitter', target: '_blank' do
        = image_tag 'share.png', class: 'share-img'
          
  .card-content
    = article.content

= javascript_pack_tag 'article'

app/views/commons/_articles.html.haml
.container
  %div
    = link_to new_article_path do
      = image_tag 'photo-camera.png', class: 'back-img'

  .home-btn
    -if signed_in?
      = button_to 'LOGOUT', destroy_user_session_path, method: :delete
    -else
      = button_to 'LOGIN', new_user_session_path, method: :post

  .home-btn
    -if current_page?(root_path)
      = button_to 'POPULAR', popular_path, method: :get
    -else
      = button_to 'TIMELINE', root_path, method: :get
  
  - articles.each do |article|
    = render 'commons/article', article: article

app/views/commons/_back_image.html.haml
= link_to 'javascript:history.back()' do
  = image_tag 'Group.png', class: 'back-img'

app/views/commons/_change_avatar.html.haml
.popup-overlay
  .popup-content
    = form_with(model: Profile, url: profile_path, method: 'put', local: true) do |f|
      %div
        = f.label :avatar, 'Avatar'
      %div
        = f.file_field :avatar, class: 'text'   
      %div
        = f.submit 'Submit', class: 'btn-submit'
    %button.close cancel

app/views/commons/_follow.html.haml
.follow-page
  = link_to account_path(user) do
    = image_tag user.avatar_image, class: 'avatar-secondary'
  %div  
  %p.article-page_username.follow_username= user.username
%hr

app/views/commons/_profile.html.haml
.container
  %div
    = link_to 'javascript:history.back()' do
      = image_tag 'Group.png', class: 'back-img'

  .center-text
    = user.username
  .profile-avatar
    = image_tag user.avatar_image, class: 'avatar-primary'

  -if user == current_user
    = render 'commons/change_avatar'

  -if !current_page?(profile_path)
    - if current_user&.has_followed?(user)
      = button_to 'UnFollow', account_unfollows_path(user), class: 'unfollow-btn', remote: true
    -else
      = button_to 'Follow', account_follows_path(user), class: 'follow-btn', remote: true

  .breadcrumb__list_primary
    ._breadcrumb__item
      %p.count= user.articles.count
    ._breadcrumb__item
      %p.count= user.followers.count
    ._breadcrumb__item
      %p.count= user.followings.count

  .breadcrumb__list_secondary
    ._breadcrumb__item
      %p.title Posts
    ._breadcrumb__item
      = link_to 'Follower', account_followers_path(user)
    ._breadcrumb__item
      = link_to 'Follow', account_followings_path(user)
  
= javascript_pack_tag 'profile'